reset;

model Part2.mod;
data data2.dat;

option solver cplex;

for {i in 0 .. 20}
{
	let a[1] := 0 + i*1000;
	for {j in 0 .. 20}
	{
		let a[2] := 0 + j*1000;
		solve;
		printf "%f %f %f\n", y[1], y[2], "%f\n";
		print a[1] > a1.txt;
		print a[2] > a2.txt;
		print y[1] > koszt.txt;
		print y[2] > ryzyko.txt;
		display gen_t[1], gen_t[2],gen_t[3];
		#display t_mach_comp[1,1], t_mach_comp[1,2], t_mach_comp[1,3], t_mach_comp[1,4], t_mach_comp[1,5];
	}
	
	
}

